version: "3"
services:
  rust-example-cn:
    build:
      context: .
    image: registry.cn-beijing.aliyuncs.com/rust/rust-by-example-cn:2019-12-26
    command: " mdbook serve -n 0.0.0.0 -p 3000"

    ports: 
      - "3000:3000"
    restart: always
    volumes:
      - "./rust-by-example-cn:/data/rust-by-example-cn"


